language: node_js
node_js:
  - 7.7.3
cache:
  npm: true # this cashes ~/.npm folder on Travis
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
addons:
  chrome: stable
before_install:
  - npm i -g npm@5
  - npm i -g firebase-tools
  - npm cache verify
install:
  - npm i
script:
  - $(npm bin)/cypress run --record
