language: node_js

node_js:
  - 10
  -
cache:
  directories:
    - ~/.npm
    - ~/.cache

addons:
  chrome: stable

before_install:
  - npm i -g firebase-tools@'latest'
  - npm cache verify

install:
  - npm i

before_script:
  - npm start -- --silent &

script:
  - npm run test
